# Regression Model Development

## Objectives

This notebook develops and evaluates multiple regression algorithms using the prepared regression dataset.

The objectives are:

- Build multiple regression models
- Compare model performance
- Evaluate using regression metrics
- Select the best-performing model
- Save the trained model for future predictions

In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import matplotlib.pyplot as plt
import seaborn as sns

import joblib

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
regression_df = pd.read_csv(
    "../data/processed/regression_data.csv"
)

regression_df.head()

   Employee_ID  KPI  Attendance Rating
0            1   89          47    Low
1            2   30           6     No
2            3   84          57      C
3            4   71          59     No
4            5   32           2     No

In [3]:
print(regression_df.columns.tolist())

['Employee_ID', 'KPI', 'Attendance', 'Rating']

In [4]:
# Replace "TargetColumn" with the actual target column name

X = regression_df.drop("TargetColumn", axis=1)

y = regression_df["TargetColumn"]

print("Feature Matrix Shape :", X.shape)
print("Target Vector Shape :", y.shape)

KeyError: "['TargetColumn'] not found in axis"

In [5]:
regression_df.columns

Index(['Employee_ID', 'KPI', 'Attendance', 'Rating'], dtype='str')

In [6]:
print(regression_df.columns.tolist())

['Employee_ID', 'KPI', 'Attendance', 'Rating']

In [7]:
X = regression_df.drop(
    ["Employee_ID", "Rating"],
    axis=1
)

y = regression_df["Rating"]

print("Feature Matrix Shape :", X.shape)
print("Target Vector Shape :", y.shape)

Feature Matrix Shape : (200, 2)
Target Vector Shape : (200,)

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)
print("Training Labels   :", y_train.shape)
print("Testing Labels    :", y_test.shape)

Training Features : (160, 2)
Testing Features  : (40, 2)
Training Labels   : (160,)
Testing Labels    : (40,)

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Feature scaling completed successfully.")

Feature scaling completed successfully.

In [10]:
from sklearn.linear_model import LinearRegression

linear_model = LinearRegression()

linear_model.fit(X_train, y_train)

print("Linear Regression model trained successfully.")

ValueError: could not convert string to float: 'C'

In [11]:
regression_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  200 non-null    int64
 1   KPI          200 non-null    int64
 2   Attendance   200 non-null    int64
 3   Rating       200 non-null    str
dtypes: int64(3), str(1)
memory usage: 6.4 KB

In [12]:
print(regression_df.dtypes)

Employee_ID    int64
KPI            int64
Attendance     int64
Rating           str
dtype: object

In [13]:
print(regression_df.head())

   Employee_ID  KPI  Attendance Rating
0            1   89          47    Low
1            2   30           6     No
2            3   84          57      C
3            4   71          59     No
4            5   32           2     No

In [14]:
regression_df = pd.read_csv("../data/processed/regression_data.csv")

regression_df.head()

   Employee_ID  KPI  Attendance Rating
0            1   89          47    Low
1            2   30           6     No
2            3   84          57      C
3            4   71          59     No
4            5   32           2     No